<?php

return [
    'alerts' => [
        'cooldown_seconds' => 300,
        'channels' => ['operations_alerts'],
    ],

    'thresholds' => [
        'sensitive_write_rate_per_minute' => 120,
        'sensitive_write_warning_ratio' => 0.85,
        'sensitive_write_critical_ratio' => 1.0,
        'monitoring_snapshot_ttl_seconds' => 30,
        'monitoring_alert_cooldown_seconds' => 120,
        'failed_jobs_warning' => 5,
        'failed_jobs_critical' => 20,
        'alerts_per_15m_warning' => 15,
        'alerts_per_15m_critical' => 40,
        'write_pressure_warning' => 80,
        'write_pressure_critical' => 140,
        'active_delivery_warning' => 120,
        'active_delivery_critical' => 220,
        'sla_on_time_warning_percent' => 85,
        'sla_on_time_critical_percent' => 70,
    ],

    'monitoring' => [
        'loop_interval_seconds' => 60,
    ],

    'security' => [
        'enforce_in_tests' => (bool) env('OPERATIONS_ENFORCE_IN_TESTS', true),
        'use_default_grants_fallback' => (bool) env('OPERATIONS_USE_DEFAULT_GRANTS_FALLBACK', true),
        'permission_cache_ttl_seconds' => (int) env('OPERATIONS_PERMISSION_CACHE_TTL_SECONDS', 300),
        'permission_group_labels' => [
            'dashboard' => 'لوحة المعلومات',
            'users' => 'المستخدمون',
            'organizations' => 'الكيانات',
            'catalog' => 'الكتالوج',
            'orders' => 'الطلبات',
            'delivery' => 'التوصيل',
            'inventory' => 'المخزون',
            'finance' => 'المالية',
            'locations' => 'المواقع',
            'content' => 'المحتوى',
            'pricing' => 'التسعير',
            'reports' => 'التقارير',
            'tasks' => 'المهام',
            'settings' => 'الإعدادات',
            'access' => 'التحكم بالوصول',
            'observability' => 'السجلات والمراقبة',
            'notifications' => 'الإشعارات',
            'general' => 'عام',
        ],
        'permission_group_order' => [
            'dashboard',
            'users',
            'organizations',
            'catalog',
            'orders',
            'delivery',
            'inventory',
            'finance',
            'locations',
            'content',
            'pricing',
            'reports',
            'tasks',
            'settings',
            'access',
            'observability',
            'notifications',
            'general',
        ],

        'sensitive_route_name_patterns' => [
            'agent' => ['agent.*', 'api.v1.agent.*'],
            'branch' => ['branch.*', 'api.v1.branch.*'],
            'distributor' => ['distributor.*', 'api.v1.distributor.*'],
            'customer' => ['customer.*', 'api.v1.customer.*'],
            'consumer' => ['consumer.*', 'api.v1.consumer.*'],
            'pos' => ['pos.*', 'api.v1.pos.*'],
            'workshop' => ['workshop.*', 'api.v1.workshop.*'],
        ],

        'permission_map' => [
            'agent' => [
                'agent.logout' => 'session.logout',
                'agent.profile.*' => 'profile.manage',
                'agent.alerts.*' => 'alerts.manage',
                'agent.branches.*' => 'branches.manage',
                'agent.distributors.*' => 'distributors.manage',
                'agent.users.*' => 'users.manage',
                'agent.commercial-stores.*' => 'customers.commercial.manage',
                'agent.wholesale-traders.*' => 'customers.commercial.manage',
                'agent.workshops.*' => 'customers.workshop.manage',
                'agent.products.*' => 'catalog.manage',
                'agent.inventory.*' => 'inventory.manage',
                'agent.orders.*' => 'orders.manage',
                'agent.replenishment.*' => 'replenishment.manage',
                'agent.reports.alerts.*' => 'reports.alerts.manage',
                'agent.payments.*' => 'finance.manage',
            ],
            'branch' => [
                'branch.logout' => 'session.logout',
                'branch.profile.*' => 'profile.manage',
                'branch.users.*' => 'users.manage',
                'branch.distributors.*' => 'distributors.manage',
                'branch.products.*' => 'catalog.manage',
                'branch.inventory.*' => 'inventory.manage',
                'branch.orders.*' => 'orders.manage',
                'branch.replenishment.*' => 'replenishment.manage',
                'branch.alerts.*' => 'alerts.manage',
                'branch.payments.*' => 'finance.manage',
            ],
            'distributor' => [
                'distributor.logout' => 'session.logout',
                'distributor.profile.*' => 'profile.manage',
                'distributor.orders.*' => 'orders.manage',
                'distributor.alerts.*' => 'alerts.manage',
                'distributor.payments.*' => 'finance.manage',
            ],
            'customer' => [
                'customer.logout' => 'session.logout',
                'customer.profile.*' => 'profile.manage',
                'customer.wholesale.products.*' => 'profile.manage',
                'customer.payment-methods.*' => 'profile.manage',
                'customer.wholesale.orders.*' => 'profile.manage',
            ],
            'consumer' => [
                'consumer.logout' => 'session.logout',
                'consumer.profile.*' => 'profile.manage',
                'consumer.addresses.*' => 'addresses.manage',
                'consumer.orders.*' => 'orders.manage',
                'consumer.ratings.*' => 'ratings.manage',
                'consumer.history.*' => 'history.actions.manage',
                'consumer.alerts.*' => 'alerts.manage',
            ],
            'pos' => [
                'pos.logout' => 'session.logout',
                'pos.profile.*' => 'profile.manage',
                'pos.catalog.*' => 'catalog.manage',
                'pos.customers.*' => 'customers.manage',
                'pos.marketplace.*' => 'marketplace.manage',
                'pos.sales.*' => 'sales.manage',
                'pos.alerts.*' => 'alerts.manage',
                'api.v1.pos.*' => 'api.access',
            ],
            'workshop' => [
                'workshop.logout' => 'session.logout',
                'workshop.profile.*' => 'profile.manage',
                'workshop.services.*' => 'services.manage',
                'workshop.marketplace.*' => 'marketplace.manage',
                'workshop.orders.*' => 'orders.manage',
                'workshop.appointments.*' => 'appointments.manage',
                'workshop.execution.*' => 'execution.manage',
                'api.v1.workshop.*' => 'api.access',
            ],
        ],

        'default_grants' => [
            'agent' => [
                'session.logout',
                'profile.manage',
                'alerts.manage',
                'branches.manage',
                'distributors.manage',
                'users.manage',
                'customers.commercial.manage',
                'customers.workshop.manage',
                'catalog.manage',
                'inventory.manage',
                'orders.manage',
                'replenishment.manage',
                'reports.alerts.manage',
                'finance.manage',
            ],
            'branch' => [
                'session.logout',
                'profile.manage',
                'users.manage',
                'distributors.manage',
                'catalog.manage',
                'inventory.manage',
                'orders.manage',
                'replenishment.manage',
                'alerts.manage',
                'finance.manage',
            ],
            'distributor' => [
                'session.logout',
                'profile.manage',
                'orders.manage',
                'alerts.manage',
                'finance.manage',
            ],
            'customer' => [
                'session.logout',
                'profile.manage',
            ],
            'consumer' => [
                'session.logout',
                'profile.manage',
                'addresses.manage',
                'orders.manage',
                'ratings.manage',
                'history.actions.manage',
                'alerts.manage',
            ],
            'pos' => [
                'session.logout',
                'profile.manage',
                'catalog.manage',
                'customers.manage',
                'marketplace.manage',
                'sales.manage',
                'alerts.manage',
                'api.access',
            ],
            'workshop' => [
                'session.logout',
                'profile.manage',
                'services.manage',
                'marketplace.manage',
                'orders.manage',
                'appointments.manage',
                'execution.manage',
                'api.access',
            ],
        ],
    ],
];
